server:
  port: 9090

zuul:
  #Service will be mapped under the /api URI
  prefix: /api
  routes:
    cart_service:
      path: /cart/v1/**
      url: http://localhost:9006
    products_service:
      path: /product/v1/**
      url: http://localhost:9009
    user_service:
      path: /user/v1/**
      url: http://localhost:9005
    order_service:
      path: /order/v1/**
      url: http://localhost:9003
    



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

spring:
  application:
    name: zuul-service